language: cpp
os: linux
services: docker
sudo: required

env:
    matrix:
        - SCAN="scan-build --status-bugs"
        - RELEASE=1
    global:
        - EVAL_GCC="CC=gcc-7 && CXX=g++-7"

matrix:
    fast_finish: true

addons:
    apt:
      sources:
        - sourceline: 'ppa:jokva/backports' # cppcheck
        - george-edison55-precise-backports # cmake 3
        - ubuntu-toolchain-r-test
      packages:
        - cppcheck
        - cmake
        - cmake-data
        - g++-7
        - libfftw3-dev
        - libgomp1
        - python3
        - python3-pip

before_install:
    - eval "${EVAL_GCC}"
    - git clone https://github.com/jokva/segyio
    - git clone https://github.com/eigenteam/eigen-git-mirror eigen
    - mkdir -p segyio/build eigen/build build build-skylake x86-64 skylake

install:
    - python3 -m pip install --user --upgrade pip setuptools setuptools-scm
    - python3 -m pip install --user segyio
    - pushd segyio/build
    - git fetch && git checkout experimental-c++-interface
    - cmake -DBUILD_SHARED_LIBS=OFF
            -DCMAKE_BUILD_TYPE=Release
            -DBUILD_PYTHON=OFF
            -DBUILD_TESTING=OFF
            -DEXPERIMENTAL=ON
            -DSEGYIO_NO_GIT_VER=ON
            ..
    - make && sudo make install
    - popd
    - pushd eigen/build
    - cmake -DBUILD_SHARED_LIBS=OFF
            -DCMAKE_BUILD_TYPE=Release
            ..
    - make
    - sudo make install
    - popd

before_script:
    - pushd build
    - $SCAN cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
                  -DBUILD_SHARED_LIBS=OFF
                  -DCMAKE_BUILD_TYPE=Release
                  -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/x86-64
                  ..
    - cppcheck --enable=style,portability,performance,warning
               --library=posix
               --suppressions-list=$TRAVIS_BUILD_DIR/cppcheck/suppressions.txt
               --inline-suppr
               --project=compile_commands.json
               --error-exitcode=1
    - popd
    - pushd build-skylake
    - cmake -DBUILD_SHARED_LIBS=OFF
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_CXX_FLAGS=-march=skylake
            -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/skylake
            ..
    - popd

script:
    - pushd build
    - $SCAN make
    - make test
    - make diff
    - make install
    - popd
    - pushd build-skylake
    - make
    - make install
    - popd
