language: cpp
os: linux
services: docker
sudo: required

matrix:
    fast_finish: true

before_install:
    - docker build --tag centos --file travis/Dockerfile .
    - eval "${EVAL_GCC}"
    - git clone https://github.com/statoil/segyio
    - git clone https://github.com/eigenteam/eigen-git-mirror eigen
    - mkdir cppcheck-src
    - pushd cppcheck-src
    - git clone https://github.com/danmar/cppcheck
    - pushd cppcheck
    - git checkout 1.87
    - popd
    - popd

script:
    - docker run --volume $PWD:/io centos
             scl enable devtoolset-7 rh-python38 /io/travis/make-release.sh

before_deploy:
    - tar cvzf simpli-$TRAVIS_TAG.tar.gz x86-64 skylake

deploy:
    - provider: releases
      skip_cleanup: true
      file:
        - simpli-$TRAVIS_TAG.tar.gz
      on:
        tags: true
      api_key:
        secure: "C670UckfgolBfZajeLRhAw3P+gLg4YGOqd/gK68OMD/z4z9V341gMAAGd0pagGvoK3WPBlg4C2GAXN5ufFTs0l6dCgt5mBo09bu94B0kwG2EUVwng9kO/8td++Ed1yVQK7bzEt4mj3mlnZ3Mi5+0n9oQWqYy3ZZYC50kyIullq3Hn6726vCEdobeCUlAsJrNz0z0ooA5hIxq9Ku2plRU1FPwv7wur+lQyCIFu9+oxMbyrKs08r0AUypM/lRxBtTYjqvLy+VFmg66NV0Pg9naoiCWX5Tc8zK4gn68B2ALMpj0YPtHvq6+ZeSnkyOvbFtWzrPoQ8PpWbGiL4UNLwtMeKIpuWccPxFzKqJDtqIiTUiwvBtsFKhbdZStBdKauChL87zov+b/QhXI9VMf6hjqJ6ZmVOQMpTWTe/XjFsW6purGVIU2kov1xfheDMQ+P893XDhpiTblOktyu3EWEV1eRlAXFnjjmiuIUg07+InbDvmRIS2Xjg5hMGCmtBYr/WbYnV7uiIZ8LoNf7pDCDenHtLVGspR5T0k7+2vIh2/CUh/JxApCq3a6mf2Z/DHy/R3XMNp7s8p1qA9bo0kT3l1jHxuvXG2aXiO467Qn+59dQGxKcD5Q02ovicRZkAvSpAVsBdXgjJKUpUnRbxJAodEMOt4dfaqFQZ/MqacBhefkSZM="